### ISSUE TITLE
domtagger error after yarn install

### ISSUE THREAD

**Issue by bennyvi** [biotope/biotope-element#73] opened 2019-01-07 14:38 UTC
**To Reproduce**
1. install with 'yarn add' 
2. start serve with yarn/(npm) start
3. check the debugging console (F12)
4. See Domtagger Error

**Comment by jurekbarth** [comment] 2019-01-07 20:10
It doesn‘t happen using npm, we should add e2e tests in order to test against these kind if issues.

**Comment by jurekbarth** [comment] 2019-05-16 06:33
I'll close this as i cannot reproduce 👍 Please reopen if necessary.

**Closed by jurekbarth** 2019-05-16 06:33 UTC
Labels: bug
